dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.3.1
  - OpenZeppelin/openzeppelin-contracts@4.4.2

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"

networks:
  default: polygon-test
  polygon-test:
    vrf_coordinator: "0x8C7382F9D8f56b33781fE506E897a4F1e2d17255"
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    key_hash: "0x6e75b569a01ef56d18cab6a8e71e6600d6ce853834d4a5748b720d06f878b3a4"
    fee: 100000000000000000 # .1 link

wallets:
  from_key: ${PRIVATE_KEY}
